[task_config]
includes = [
  ".bootstrap/.mise/tasks",
  ".mise/tasks",
]

[env]

## <<Stencil::Block(customMiseEnvironment)>>
GO_MODULES_TO_SYNC="github.com/getoutreach/gobox"
IGNORED_GO_MOD_DIRS="templates/.snapshots/testdata"
## <</Stencil::Block>>

[tools]
"npm:prettier" = "2"

## <<Stencil::Block(customMiseTools)>>

## <</Stencil::Block>>

## <<Stencil::Block(extraMise)>>

## <</Stencil::Block>>
